create_joke:
  description: >
    Create a funny joke about {topic}. The joke should be
    original, appropriate, and entertaining. Format it nicely
    with setup and punchline.
  expected_output: >
    A funny joke about the given topic
