find_latest_videos:
  description: >
    Search and collect the 3 most recent videos from the specified YouTube channel {channel}.
    Return only the video URLs in a list format.
    The videos should be sorted by upload date with the most recent first.
  expected_output: >
    A list containing URLs of the 3 most recent videos from the channel

fetch_videos_information:
  description: >
    Research and gather detailed information about a specific YouTube video.
    Include the following details:
    - Video URL
    - Video title
    - Upload date
    - View count
    - Description
    - Main topics or themes discussed
    - Key highlights or summary
  expected_output: >
    A comprehensive summary containing all the requested video information and analysis

create_joke:
  description: >
    Create a funny joke about one of recent videos from youtube channel {channel}
    The joke should be original, appropriate, and entertaining.
    Format it nicely with setup and punchline.
  expected_output: >
    A funny joke about the given topic
