find_latest_videos:
  description: >
    Search and collect the 5 most recent videos from the specified YouTube channel {channel}.
    Return only the video URLs in a list format.
    The videos should be sorted by upload date with the most recent first.
  expected_output: >
    A list containing URLs of the 5 most recent videos from the channel

fetch_videos_information:
  description: >
    Research and gather detailed information about a specific YouTube video.
  expected_output: >
    A comprehensive summary containing all the requested video information and analysis

create_joke:
  description: >
    Create a funny joke about one of recent videos from youtube channel {channel}
    The joke should be original, appropriate, and entertaining.
    Format it nicely with setup and punchline.
  expected_output: >
    A funny joke about the given topic

research_channel:
  description: >
    Research and gather comprehensive information about the YouTube channel {channel}.
    Include details such as:
    - Channel description and main content focus
    - Subscriber count and total views
    - Creation date
    - Upload frequency
    - Popular video categories
    - Any notable achievements or milestones
  expected_output: >
    A detailed summary of the channel's profile, statistics, and content strategy
